# Generated by Django 4.2.8 on 2023-12-18 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "o_id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("o_search_keyword", models.CharField(max_length=255)),
                ("o_title", models.CharField(max_length=255)),
                ("o_department_code", models.IntegerField()),
                ("o_city_code", models.IntegerField()),
                ("o_city", models.CharField(max_length=100, null=True)),
                ("o_company_name", models.CharField(max_length=255, null=True)),
                ("o_description", models.TextField(null=True)),
                ("o_contract", models.CharField(max_length=100, null=True)),
                ("o_contact_mail", models.EmailField(max_length=254, null=True)),
                ("o_added_at", models.DateTimeField(null=True)),
                ("o_updated_at", models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("exigence", models.CharField(max_length=1)),
                (
                    "offer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="joboffers.offer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Salary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "min_salary",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "max_salary",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                ("salary_description", models.TextField(null=True)),
                (
                    "offer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salary",
                        to="joboffers.offer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Geolocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(decimal_places=6, max_digits=9, null=True),
                ),
                (
                    "longitude",
                    models.DecimalField(decimal_places=6, max_digits=9, null=True),
                ),
                (
                    "offer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="geolocation",
                        to="joboffers.offer",
                    ),
                ),
            ],
        ),
    ]
